import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ArchiveCard from '../components/archive'
import styles from '../styles/Projects.module.css'

const Archive: NextPage = () => {
    return (
        <div className={styles.projects}>
             <Head>
                <title>Phyf3 - Archive</title>
                <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="https://fav.farm/🐱‍👤" />
            </Head>

            <main>
                <ArchiveCard/>
            </main>
        </div>
     ) 
}

export default Archive