import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Intro from '../components/introductions'
import About from '../components/about'
import Projects from '../components/projects'
import ContactIcons from '../components/contact_icons'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Phyf3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://fav.farm/🐱‍👤" />
      </Head>
      

      <main className={styles.main}>
        <div className={styles.left} >
          <ContactIcons/>

          <div></div>
        </div>

        <div className={styles.content}>
          <Intro/>
          <About/>
          <Projects/>

          <section className={styles.contact}> 
            <div>
            <h1>03.</h1>
            <p>Feel free to reach out!</p>
            <ContactIcons/>
            </div>
          </section>
        </div>
        

        <div className={styles.right}>
          <p> Phyf3script@gmail.com</p>
         </div>
      </main>
      
      <footer >
        <p>Inspired by <span><Link href="https://brittanychiang.com">brittanychiang.com</Link></span>  </p>
      </footer>
    </div>
  )
}

export default Home
