import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Projects.module.css'

const Projects: NextPage = () => {
    return (
        <div className={styles.projects}>
             <Head>
                <title>Phyf3</title>
                <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
     ) 
}

export default Projects